### ISSUE TITLE
The package could not be found on the pub

### ISSUE THREAD

**Issue by dengsgo** [apptreesoftware/flutter_webview#1]
Can you upload this package to pub.dartlang.org ?

**Comment by matthewtsmith** [comment]
@dengsgo I will be uploading this to pub later today. We have a little cleanup to do first. Until it's published you can add it to your pubspec dependencies like this:

```
flutter_web_view:
    git: git://github.com/apptreesoftware/flutter_webview
```

**Comment by matthewtsmith** [comment]
This has been published [here](https://pub.dartlang.org/packages/flutter_web_view)
