### ISSUE TITLE
Unable to build Android application, Type Mismatch inferred type. 

### ISSUE THREAD

**Issue by Joran-Dob** [apptreesoftware/flutter_webview#20]
When using the package and building for android, there is an fatal compilation error:

`e: /Users/.pub-cache/hosted/pub.dartlang.org/flutter_web_view-0.0.3/android/src/main/kotlin/com/apptreesoftware/flutterwebview/FlutterWebViewPlugin.kt: (92, 45): Type mismatch: inferred type is String? but String was expected
e: /Users/.pub-cache/hosted/pub.dartlang.org/flutter_web_view-0.0.3/android/src/main/kotlin/com/apptreesoftware/flutterwebview/FlutterWebViewPlugin.kt: (92, 50): Type mismatch: inferred type is Boolean? but Boolean was expected
e: /Users/.pub-cache/hosted/pub.dartlang.org/flutter_web_view-0.0.3/android/src/main/kotlin/com/apptreesoftware/flutterwebview/FlutterWebViewPlugin.kt: (107, 39): Type mismatch: inferred type is String? but String was expected
`
It seems that type checking, if the value has not been done one these values? #

**Comment by abacaj** [comment]
This package is useless on android at the moment:

```
e: /Users/anton/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_view-0.0.3/android/src/main/kotlin/com/apptreesoftware/flutterwebview/FlutterWebViewPlugin.kt: (92, 45): Type mismatch: inferred type is String? but String was expected
e: /Users/anton/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_view-0.0.3/android/src/main/kotlin/com/apptreesoftware/flutterwebview/FlutterWebViewPlugin.kt: (92, 
50): Type mismatch: inferred type is Boolean? but Boolean was expected
e: /Users/anton/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_view-0.0.3/android/src/main/kotlin/com/apptreesoftware/flutterwebview/FlutterWebViewPlugin.kt: (107, 39): Type mismatch: inferred type is String? but String was expected
```

**Comment by Joran-Dob** [comment]
@abacaj Please try my fork: https://github.com/Joran-Dob/flutter_webview 

I should work, I already opened a pull request but it seems the devs are not really active on this project

**Comment by rupert2133** [comment]
> 
> 
> @abacaj Please try my fork: https://github.com/Joran-Dob/flutter_webview
> 
> I should work, I already opened a pull request but it seems the devs are not really active on this project

@Joran-Dob Not working. Please help

**Comment by matthewtsmith** [comment]
@Joran-Dob I commented on your PR with a change we'd like to see. Once that is resolved I'll merge and publish a new version.

**Comment by matthewtsmith** [comment]
Fixed in latest release.
