### ISSUE TITLE
App Store Connect: ITMS-90809: Deprecated API Usage 

### ISSUE THREAD

**Issue by willladislaw** [apptreesoftware/flutter_webview#36]
App Store Connect has now began to flag the package as deprecated.

"ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview)."

**Comment by willladislaw** [comment]
Any feedback?

**Comment by matthewtsmith** [comment]
@willladislaw This plugin is not in active development. I suggest switching to the community supported plugin: https://pub.dev/packages/flutter_webview_plugin

**Comment by willladislaw** [comment]
Thanks.
